Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 3, Cries
	dba Cry_Boyhyrax
	dba Cry_Girlhyrax
	dba Cry_Beaver
	dba Cry_Kangaroo
	dba Cry_Salamander
	dba Cry_Grime
	dba Cry_Explosive
	dba Cry_Mud
	dba Cry_Radish
	dba Cry_Jerboa
	dba Cry_Kaijuqueen
	dba Cry_Mole
	dba Cry_Seal
	dba Cry_Tapir
	dba Cry_Pigeon
	dba Cry_Bulbasaur
	dba Cry_Sparrow
	dba Cry_Rock_Kaiju
	dba Cry_Rubble
	dba Cry_Bad_Turtle
	dba Cry_Osprey
	dba Cry_Larva
	dba Cry_Caterpilla
	dba Cry_Snake
	dba Cry_Vulture
	dba Cry_Clefairy
	dba Cry_Gnat
	dba Cry_Plesiosaur
	dba Cry_Chrysalis
	dba Cry_Sea_Turtle
	dba Cry_Nymph
	dba Cry_Kai_Ken
	dba Cry_Crab
	dba Cry_Fluffyduck
	dba Cry_Rat
	dba Cry_Rafflesia
	dba Cry_Fox
	dba Cry_Drysprout
	dba Cry_Water_Rat
	dba Cry_Spider
	dba Cry_Hobo_Clown
	dba Cry_Giraffe
	dba Cry_Barghest
	dba Cry_Lamb
	dba Cry_BadClown
	dba Cry_Owl
	dba Cry_Raccoon
	dba Cry_Warlock
	dba Cry_Skunk
	dba Cry_Squirrel
	dba Cry_Caiman
	dba Cry_Gligar
	dba Cry_Cleffa
	dba Cry_Slug
	dba Cry_Ladybug
	dba Cry_Cerberus
	dba Cry_Shags2Dope
	dba Cry_Manta
	dba Cry_Badger
	dba Cry_Kakapo
	dba Cry_Teddybear
	dba Cry_Sunflower
	dba Cry_Ram
	dba Cry_Snail
	dba Cry_Gerbil
	dba Cry_Chimpanzee
	dba Cry_Tsuchinoko
	dba Cry_Elephant
	assert_table_length NUM_CRIES
