AnimationPointers:
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw SalamanderAnimation
	dw ChameleonAnimation
	dw DragonAnimation
	dw Sea_TurtleAnimation
	dw TortoiseAnimation
	dw Bad_TurtleAnimation
	dw CaterpieAnimation
	dw ChrysalisAnimation
	dw ButterflyAnimation
	dw WeedleAnimation
	dw PupaAnimation
	dw BeeAnimation
	dw PidgeyAnimation
	dw OspreyAnimation
	dw EagleAnimation
	dw RattataAnimation
	dw MoleratAnimation
	dw SparrowAnimation
	dw VultureAnimation
	dw SnakeAnimation
	dw CobraAnimation
	dw ClickerAnimation
	dw JerboaAnimation
	dw ShrewAnimation
	dw EchidnaAnimation
	dw NidoranFAnimation
	dw JanekalopeAnimation
	dw KaijuqueenAnimation
	dw NidoranMAnimation
	dw JackalopeAnimation
	dw KaijukingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw FoxAnimation
	dw KitsuneAnimation
	dw BloonbunchAnimation
	dw BloondogAnimation
	dw ZubatAnimation
	dw Scary_BatAnimation
	dw RadishAnimation
	dw MandrakeAnimation
	dw RafflesiaAnimation
	dw NymphAnimation
	dw HermitcrabAnimation
	dw GnatAnimation
	dw MothAnimation
	dw MoleAnimation
	dw ThreeMolesAnimation
	dw CatAnimation
	dw CougarAnimation
	dw FluffyduckAnimation
	dw KappaAnimation
	dw MonkeyAnimation
	dw GorillaAnimation
	dw Kai_KenAnimation
	dw ShisaAnimation
	dw PoliwagAnimation
	dw LegtadpoleAnimation
	dw ToadAnimation
	dw AbraAnimation
	dw HagabondAnimation
	dw HomelassAnimation
	dw ScrawnyAnimation
	dw HunkAnimation
	dw BeefcakeAnimation
	dw BeansproutAnimation
	dw DrysproutAnimation
	dw MungsproutAnimation
	dw JELLYFISHAnimation
	dw ManowarAnimation
	dw RockyAnimation
	dw Hard_RockAnimation
	dw RubbleAnimation
	dw PonyAnimation
	dw HorseAnimation
	dw BeaverAnimation
	dw Sazae_OniAnimation
	dw MagnetAnimation
	dw ElectromagAnimation
	dw DuckAnimation
	dw DodoAnimation
	dw Two_DodosAnimation
	dw SealAnimation
	dw DugongAnimation
	dw GrimeAnimation
	dw MudAnimation
	dw ClamAnimation
	dw OysterAnimation
	dw DrifterAnimation
	dw SpookyAnimation
	dw PhantomAnimation
	dw WyrmAnimation
	dw TapirAnimation
	dw BakuAnimation
	dw CrabAnimation
	dw Coco_CrabAnimation
	dw ExplosiveAnimation
	dw BombAnimation
	dw Dozen_EggsAnimation
	dw CoconutsAnimation
	dw Cave_ManAnimation
	dw Cave_OgreAnimation
	dw Bruce_LeeAnimation
	dw JackieChanAnimation
	dw PervertAnimation
	dw VirusAnimation
	dw BactophageAnimation
	dw RhinoAnimation
	dw Rock_KaijuAnimation
	dw ChanseyAnimation
	dw MedusaAnimation
	dw KangarooAnimation
	dw SeahorseAnimation
	dw HydraAnimation
	dw GoldfishAnimation
	dw NarwhalAnimation
	dw StarfishAnimation
	dw SeastarAnimation
	dw CrackheadAnimation
	dw MantisAnimation
	dw Drag_QueenAnimation
	dw RaijinAnimation
	dw KaruraAnimation
	dw StagbeetleAnimation
	dw BullAnimation
	dw CarpAnimation
	dw InkanyambaAnimation
	dw PlesiosaurAnimation
	dw SlimeAnimation
	dw WolfAnimation
	dw Wet_DogAnimation
	dw GreyhoundAnimation
	dw Hot_DogAnimation
	dw LopolyfaceAnimation
	dw NautilusAnimation
	dw CuttlefishAnimation
	dw Shoe_CrabAnimation
	dw SeascorpioAnimation
	dw PteranodonAnimation
	dw PandaAnimation
	dw YetiAnimation
	dw ThundabirdAnimation
	dw FirebirdAnimation
	dw SerpentAnimation
	dw LeviathanAnimation
	dw MascotAnimation
	dw WendigoAnimation
	dw BrainAnimation
	dw ChikoritaAnimation
	dw KoalaAnimation
	dw SlothAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw MonitorAnimation
	dw CrocodileAnimation
	dw SentretAnimation
	dw FerretAnimation
	dw HoothootAnimation
	dw HornedowlAnimation
	dw LedybaAnimation
	dw FireflyAnimation
	dw SpinarakAnimation
	dw WaspAnimation
	dw Big_BatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw GerbilAnimation
	dw CleffaAnimation
	dw BalloonAnimation
	dw Hobo_ClownAnimation
	dw BadClownAnimation
	dw KakapoAnimation
	dw QuetzalAnimation
	dw LambAnimation
	dw SheepAnimation
	dw RamAnimation
	dw Hula_GirlAnimation
	dw Water_RatAnimation
	dw RabbitAnimation
	dw Fake_BushAnimation
	dw FrogAnimation
	dw HoppipAnimation
	dw DaisyAnimation
	dw DandelionAnimation
	dw ChimpanzeeAnimation
	dw SeedAnimation
	dw SunflowerAnimation
	dw DragonflyAnimation
	dw Shags2DopeAnimation
	dw Violent_JAnimation
	dw TerrierAnimation
	dw Xolo_DogAnimation
	dw CrowAnimation
	dw WarlockAnimation
	dw BansheeAnimation
	dw LettahAnimation
	dw RolypolyAnimation
	dw GiraffeAnimation
	dw PineconeAnimation
	dw FortressAnimation
	dw TsuchinokoAnimation
	dw GligarAnimation
	dw DeathwormAnimation
	dw FrenchieAnimation
	dw BulldogAnimation
	dw BlowfishAnimation
	dw MantidflyAnimation
	dw ScalebugAnimation
	dw BeetleAnimation
	dw WeaselAnimation
	dw TeddybearAnimation
	dw BearAnimation
	dw SlugAnimation
	dw SnailAnimation
	dw BoarAnimation
	dw MammothAnimation
	dw CoralAnimation
	dw RemoraAnimation
	dw OctopusAnimation
	dw SantaAnimation
	dw MantaAnimation
	dw CondorAnimation
	dw RottweilerAnimation
	dw DobermanAnimation
	dw Sea_DragonAnimation
	dw ElebabyAnimation
	dw ElephantAnimation
	dw LopolykiwiAnimation
	dw ElkAnimation
	dw ArtistAnimation
	dw John_CenaAnimation
	dw DreidelAnimation
	dw BowlcutAnimation
	dw PlugAnimation
	dw BoobyAnimation
	dw CowAnimation
	dw BlisseyAnimation
	dw BarghestAnimation
	dw CerberusAnimation
	dw FenrirAnimation
	dw RaptorAnimation
	dw IronmaidenAnimation
	dw TrexAnimation
	dw RyujinAnimation
	dw PhoenixAnimation
	dw CelebiAnimation
