BitmasksPointers:
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw SalamanderBitmasks
	dw ChameleonBitmasks
	dw DragonBitmasks
	dw Sea_TurtleBitmasks
	dw TortoiseBitmasks
	dw Bad_TurtleBitmasks
	dw CaterpieBitmasks
	dw ChrysalisBitmasks
	dw ButterflyBitmasks
	dw WeedleBitmasks
	dw PupaBitmasks
	dw BeeBitmasks
	dw PidgeyBitmasks
	dw OspreyBitmasks
	dw EagleBitmasks
	dw RattataBitmasks
	dw MoleratBitmasks
	dw SparrowBitmasks
	dw VultureBitmasks
	dw SnakeBitmasks
	dw CobraBitmasks
	dw ClickerBitmasks
	dw JerboaBitmasks
	dw ShrewBitmasks
	dw EchidnaBitmasks
	dw NidoranFBitmasks
	dw JanekalopeBitmasks
	dw KaijuqueenBitmasks
	dw NidoranMBitmasks
	dw JackalopeBitmasks
	dw KaijukingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw FoxBitmasks
	dw KitsuneBitmasks
	dw BloonbunchBitmasks
	dw BloondogBitmasks
	dw ZubatBitmasks
	dw Scary_BatBitmasks
	dw RadishBitmasks
	dw MandrakeBitmasks
	dw RafflesiaBitmasks
	dw NymphBitmasks
	dw HermitcrabBitmasks
	dw GnatBitmasks
	dw MothBitmasks
	dw MoleBitmasks
	dw ThreeMolesBitmasks
	dw CatBitmasks
	dw CougarBitmasks
	dw FluffyduckBitmasks
	dw KappaBitmasks
	dw MonkeyBitmasks
	dw GorillaBitmasks
	dw Kai_KenBitmasks
	dw ShisaBitmasks
	dw PoliwagBitmasks
	dw LegtadpoleBitmasks
	dw ToadBitmasks
	dw AbraBitmasks
	dw HagabondBitmasks
	dw HomelassBitmasks
	dw ScrawnyBitmasks
	dw HunkBitmasks
	dw BeefcakeBitmasks
	dw BeansproutBitmasks
	dw DrysproutBitmasks
	dw MungsproutBitmasks
	dw JELLYFISHBitmasks
	dw ManowarBitmasks
	dw RockyBitmasks
	dw Hard_RockBitmasks
	dw RubbleBitmasks
	dw PonyBitmasks
	dw HorseBitmasks
	dw BeaverBitmasks
	dw Sazae_OniBitmasks
	dw MagnetBitmasks
	dw ElectromagBitmasks
	dw DuckBitmasks
	dw DodoBitmasks
	dw Two_DodosBitmasks
	dw SealBitmasks
	dw DugongBitmasks
	dw GrimeBitmasks
	dw MudBitmasks
	dw ClamBitmasks
	dw OysterBitmasks
	dw DrifterBitmasks
	dw SpookyBitmasks
	dw PhantomBitmasks
	dw WyrmBitmasks
	dw TapirBitmasks
	dw BakuBitmasks
	dw CrabBitmasks
	dw Coco_CrabBitmasks
	dw ExplosiveBitmasks
	dw BombBitmasks
	dw Dozen_EggsBitmasks
	dw CoconutsBitmasks
	dw Cave_ManBitmasks
	dw Cave_OgreBitmasks
	dw Bruce_LeeBitmasks
	dw JackieChanBitmasks
	dw PervertBitmasks
	dw VirusBitmasks
	dw BactophageBitmasks
	dw RhinoBitmasks
	dw Rock_KaijuBitmasks
	dw ChanseyBitmasks
	dw MedusaBitmasks
	dw KangarooBitmasks
	dw SeahorseBitmasks
	dw HydraBitmasks
	dw GoldfishBitmasks
	dw NarwhalBitmasks
	dw StarfishBitmasks
	dw SeastarBitmasks
	dw CrackheadBitmasks
	dw MantisBitmasks
	dw Drag_QueenBitmasks
	dw RaijinBitmasks
	dw KaruraBitmasks
	dw StagbeetleBitmasks
	dw BullBitmasks
	dw CarpBitmasks
	dw InkanyambaBitmasks
	dw PlesiosaurBitmasks
	dw SlimeBitmasks
	dw WolfBitmasks
	dw Wet_DogBitmasks
	dw GreyhoundBitmasks
	dw Hot_DogBitmasks
	dw LopolyfaceBitmasks
	dw NautilusBitmasks
	dw CuttlefishBitmasks
	dw Shoe_CrabBitmasks
	dw SeascorpioBitmasks
	dw PteranodonBitmasks
	dw PandaBitmasks
	dw YetiBitmasks
	dw ThundabirdBitmasks
	dw FirebirdBitmasks
	dw SerpentBitmasks
	dw LeviathanBitmasks
	dw MascotBitmasks
	dw WendigoBitmasks
	dw BrainBitmasks
	dw ChikoritaBitmasks
	dw KoalaBitmasks
	dw SlothBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw MonitorBitmasks
	dw CrocodileBitmasks
	dw SentretBitmasks
	dw FerretBitmasks
	dw HoothootBitmasks
	dw HornedowlBitmasks
	dw LedybaBitmasks
	dw FireflyBitmasks
	dw SpinarakBitmasks
	dw WaspBitmasks
	dw Big_BatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw GerbilBitmasks
	dw CleffaBitmasks
	dw BalloonBitmasks
	dw Hobo_ClownBitmasks
	dw BadClownBitmasks
	dw KakapoBitmasks
	dw QuetzalBitmasks
	dw LambBitmasks
	dw SheepBitmasks
	dw RamBitmasks
	dw Hula_GirlBitmasks
	dw Water_RatBitmasks
	dw RabbitBitmasks
	dw Fake_BushBitmasks
	dw FrogBitmasks
	dw HoppipBitmasks
	dw DaisyBitmasks
	dw DandelionBitmasks
	dw ChimpanzeeBitmasks
	dw SeedBitmasks
	dw SunflowerBitmasks
	dw DragonflyBitmasks
	dw Shags2DopeBitmasks
	dw Violent_JBitmasks
	dw TerrierBitmasks
	dw Xolo_DogBitmasks
	dw CrowBitmasks
	dw WarlockBitmasks
	dw BansheeBitmasks
	dw LettahBitmasks
	dw RolypolyBitmasks
	dw GiraffeBitmasks
	dw PineconeBitmasks
	dw FortressBitmasks
	dw TsuchinokoBitmasks
	dw GligarBitmasks
	dw DeathwormBitmasks
	dw FrenchieBitmasks
	dw BulldogBitmasks
	dw BlowfishBitmasks
	dw MantidflyBitmasks
	dw ScalebugBitmasks
	dw BeetleBitmasks
	dw WeaselBitmasks
	dw TeddybearBitmasks
	dw BearBitmasks
	dw SlugBitmasks
	dw SnailBitmasks
	dw BoarBitmasks
	dw MammothBitmasks
	dw CoralBitmasks
	dw RemoraBitmasks
	dw OctopusBitmasks
	dw SantaBitmasks
	dw MantaBitmasks
	dw CondorBitmasks
	dw RottweilerBitmasks
	dw DobermanBitmasks
	dw Sea_DragonBitmasks
	dw ElebabyBitmasks
	dw ElephantBitmasks
	dw LopolykiwiBitmasks
	dw ElkBitmasks
	dw ArtistBitmasks
	dw John_CenaBitmasks
	dw DreidelBitmasks
	dw BowlcutBitmasks
	dw PlugBitmasks
	dw BoobyBitmasks
	dw CowBitmasks
	dw BlisseyBitmasks
	dw BarghestBitmasks
	dw CerberusBitmasks
	dw FenrirBitmasks
	dw RaptorBitmasks
	dw IronmaidenBitmasks
	dw TrexBitmasks
	dw RyujinBitmasks
	dw PhoenixBitmasks
	dw CelebiBitmasks
