FramesPointers:
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw SalamanderFrames
	dw ChameleonFrames
	dw DragonFrames
	dw Sea_TurtleFrames
	dw TortoiseFrames
	dw Bad_TurtleFrames
	dw CaterpieFrames
	dw ChrysalisFrames
	dw ButterflyFrames
	dw WeedleFrames
	dw PupaFrames
	dw BeeFrames
	dw PidgeyFrames
	dw OspreyFrames
	dw EagleFrames
	dw RattataFrames
	dw MoleratFrames
	dw SparrowFrames
	dw VultureFrames
	dw SnakeFrames
	dw CobraFrames
	dw ClickerFrames
	dw JerboaFrames
	dw ShrewFrames
	dw EchidnaFrames
	dw NidoranFFrames
	dw JanekalopeFrames
	dw KaijuqueenFrames
	dw NidoranMFrames
	dw JackalopeFrames
	dw KaijukingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw FoxFrames
	dw KitsuneFrames
	dw BloonbunchFrames
	dw BloondogFrames
	dw ZubatFrames
	dw Scary_BatFrames
	dw RadishFrames
	dw MandrakeFrames
	dw RafflesiaFrames
	dw NymphFrames
	dw HermitcrabFrames
	dw GnatFrames
	dw MothFrames
	dw MoleFrames
	dw ThreeMolesFrames
	dw CatFrames
	dw CougarFrames
	dw FluffyduckFrames
	dw KappaFrames
	dw MonkeyFrames
	dw GorillaFrames
	dw Kai_KenFrames
	dw ShisaFrames
	dw PoliwagFrames
	dw LegtadpoleFrames
	dw ToadFrames
	dw AbraFrames
	dw HagabondFrames
	dw HomelassFrames
	dw ScrawnyFrames
	dw HunkFrames
	dw BeefcakeFrames
	dw BeansproutFrames
	dw DrysproutFrames
	dw MungsproutFrames
	dw JELLYFISHFrames
	dw ManowarFrames
	dw RockyFrames
	dw Hard_RockFrames
	dw RubbleFrames
	dw PonyFrames
	dw HorseFrames
	dw BeaverFrames
	dw Sazae_OniFrames
	dw MagnetFrames
	dw ElectromagFrames
	dw DuckFrames
	dw DodoFrames
	dw Two_DodosFrames
	dw SealFrames
	dw DugongFrames
	dw GrimeFrames
	dw MudFrames
	dw ClamFrames
	dw OysterFrames
	dw DrifterFrames
	dw SpookyFrames
	dw PhantomFrames
	dw WyrmFrames
	dw TapirFrames
	dw BakuFrames
	dw CrabFrames
	dw Coco_CrabFrames
	dw ExplosiveFrames
	dw BombFrames
	dw Dozen_EggsFrames
	dw CoconutsFrames
	dw Cave_ManFrames
	dw Cave_OgreFrames
	dw Bruce_LeeFrames
	dw JackieChanFrames
	dw PervertFrames
	dw VirusFrames
	dw BactophageFrames
	dw RhinoFrames
	dw Rock_KaijuFrames
	dw ChanseyFrames
	dw MedusaFrames
	dw KangarooFrames
	dw SeahorseFrames
	dw HydraFrames
	dw GoldfishFrames
	dw NarwhalFrames
	dw StarfishFrames
	dw SeastarFrames
	dw CrackheadFrames
	dw MantisFrames
	dw Drag_QueenFrames
	dw RaijinFrames
	dw KaruraFrames
	dw StagbeetleFrames
	dw BullFrames
	dw CarpFrames
	dw InkanyambaFrames
	dw PlesiosaurFrames
	dw SlimeFrames
	dw WolfFrames
	dw Wet_DogFrames
	dw GreyhoundFrames
	dw Hot_DogFrames
	dw LopolyfaceFrames
	dw NautilusFrames
	dw CuttlefishFrames
	dw Shoe_CrabFrames
	dw SeascorpioFrames
	dw PteranodonFrames
	dw PandaFrames
	dw YetiFrames
	dw ThundabirdFrames
	dw FirebirdFrames
	dw SerpentFrames
	dw LeviathanFrames
	dw MascotFrames
	dw WendigoFrames
	dw BrainFrames
	dw ChikoritaFrames
	dw KoalaFrames
	dw SlothFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw MonitorFrames
	dw CrocodileFrames
	dw SentretFrames
	dw FerretFrames
	dw HoothootFrames
	dw HornedowlFrames
	dw LedybaFrames
	dw FireflyFrames
	dw SpinarakFrames
	dw WaspFrames
	dw Big_BatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw GerbilFrames
	dw CleffaFrames
	dw BalloonFrames
	dw Hobo_ClownFrames
	dw BadClownFrames
	dw KakapoFrames
	dw QuetzalFrames
	dw LambFrames
	dw SheepFrames
	dw RamFrames
	dw Hula_GirlFrames
	dw Water_RatFrames
	dw RabbitFrames
	dw Fake_BushFrames
	dw FrogFrames
	dw HoppipFrames
	dw DaisyFrames
	dw DandelionFrames
	dw ChimpanzeeFrames
	dw SeedFrames
	dw SunflowerFrames
	dw DragonflyFrames
	dw Shags2DopeFrames
	dw Violent_JFrames
	dw TerrierFrames
	dw Xolo_DogFrames
	dw CrowFrames
	dw WarlockFrames
	dw BansheeFrames
	dw LettahFrames
	dw RolypolyFrames
	dw GiraffeFrames
	dw PineconeFrames
	dw FortressFrames
	dw TsuchinokoFrames
	dw GligarFrames
	dw DeathwormFrames
	dw FrenchieFrames
	dw BulldogFrames
	dw BlowfishFrames
	dw MantidflyFrames
	dw ScalebugFrames
	dw BeetleFrames
	dw WeaselFrames
	dw TeddybearFrames
	dw BearFrames
	dw SlugFrames
	dw SnailFrames
	dw BoarFrames
	dw MammothFrames
	dw CoralFrames
	dw RemoraFrames
	dw OctopusFrames
	dw SantaFrames
	dw MantaFrames
	dw CondorFrames
	dw RottweilerFrames
	dw DobermanFrames
	dw Sea_DragonFrames
	dw ElebabyFrames
	dw ElephantFrames
	dw LopolykiwiFrames
	dw ElkFrames
	dw ArtistFrames
	dw John_CenaFrames
	dw DreidelFrames
	dw BowlcutFrames
	dw PlugFrames
	dw BoobyFrames
	dw CowFrames
	dw BlisseyFrames
	dw BarghestFrames
	dw CerberusFrames
	dw FenrirFrames
	dw RaptorFrames
	dw IronmaidenFrames
	dw TrexFrames
	dw RyujinFrames
	dw PhoenixFrames
	dw CelebiFrames
