AnimationIdlePointers:
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw SalamanderAnimationIdle
	dw ChameleonAnimationIdle
	dw DragonAnimationIdle
	dw Sea_TurtleAnimationIdle
	dw TortoiseAnimationIdle
	dw Bad_TurtleAnimationIdle
	dw CaterpieAnimationIdle
	dw ChrysalisAnimationIdle
	dw ButterflyAnimationIdle
	dw WeedleAnimationIdle
	dw PupaAnimationIdle
	dw BeeAnimationIdle
	dw PidgeyAnimationIdle
	dw OspreyAnimationIdle
	dw EagleAnimationIdle
	dw RattataAnimationIdle
	dw MoleratAnimationIdle
	dw SparrowAnimationIdle
	dw VultureAnimationIdle
	dw SnakeAnimationIdle
	dw CobraAnimationIdle
	dw ClickerAnimationIdle
	dw JerboaAnimationIdle
	dw ShrewAnimationIdle
	dw EchidnaAnimationIdle
	dw NidoranFAnimationIdle
	dw JanekalopeAnimationIdle
	dw KaijuqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw JackalopeAnimationIdle
	dw KaijukingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw FoxAnimationIdle
	dw KitsuneAnimationIdle
	dw BloonbunchAnimationIdle
	dw BloondogAnimationIdle
	dw ZubatAnimationIdle
	dw Scary_BatAnimationIdle
	dw RadishAnimationIdle
	dw MandrakeAnimationIdle
	dw RafflesiaAnimationIdle
	dw NymphAnimationIdle
	dw HermitcrabAnimationIdle
	dw GnatAnimationIdle
	dw MothAnimationIdle
	dw MoleAnimationIdle
	dw ThreeMolesAnimationIdle
	dw CatAnimationIdle
	dw CougarAnimationIdle
	dw FluffyduckAnimationIdle
	dw KappaAnimationIdle
	dw MonkeyAnimationIdle
	dw GorillaAnimationIdle
	dw Kai_KenAnimationIdle
	dw ShisaAnimationIdle
	dw PoliwagAnimationIdle
	dw LegtadpoleAnimationIdle
	dw ToadAnimationIdle
	dw AbraAnimationIdle
	dw HagabondAnimationIdle
	dw HomelassAnimationIdle
	dw ScrawnyAnimationIdle
	dw HunkAnimationIdle
	dw BeefcakeAnimationIdle
	dw BeansproutAnimationIdle
	dw DrysproutAnimationIdle
	dw MungsproutAnimationIdle
	dw JELLYFISHAnimationIdle
	dw ManowarAnimationIdle
	dw RockyAnimationIdle
	dw Hard_RockAnimationIdle
	dw RubbleAnimationIdle
	dw PonyAnimationIdle
	dw HorseAnimationIdle
	dw BeaverAnimationIdle
	dw Sazae_OniAnimationIdle
	dw MagnetAnimationIdle
	dw ElectromagAnimationIdle
	dw DuckAnimationIdle
	dw DodoAnimationIdle
	dw Two_DodosAnimationIdle
	dw SealAnimationIdle
	dw DugongAnimationIdle
	dw GrimeAnimationIdle
	dw MudAnimationIdle
	dw ClamAnimationIdle
	dw OysterAnimationIdle
	dw DrifterAnimationIdle
	dw SpookyAnimationIdle
	dw PhantomAnimationIdle
	dw WyrmAnimationIdle
	dw TapirAnimationIdle
	dw BakuAnimationIdle
	dw CrabAnimationIdle
	dw Coco_CrabAnimationIdle
	dw ExplosiveAnimationIdle
	dw BombAnimationIdle
	dw Dozen_EggsAnimationIdle
	dw CoconutsAnimationIdle
	dw Cave_ManAnimationIdle
	dw Cave_OgreAnimationIdle
	dw Bruce_LeeAnimationIdle
	dw JackieChanAnimationIdle
	dw PervertAnimationIdle
	dw VirusAnimationIdle
	dw BactophageAnimationIdle
	dw RhinoAnimationIdle
	dw Rock_KaijuAnimationIdle
	dw ChanseyAnimationIdle
	dw MedusaAnimationIdle
	dw KangarooAnimationIdle
	dw SeahorseAnimationIdle
	dw HydraAnimationIdle
	dw GoldfishAnimationIdle
	dw NarwhalAnimationIdle
	dw StarfishAnimationIdle
	dw SeastarAnimationIdle
	dw CrackheadAnimationIdle
	dw MantisAnimationIdle
	dw Drag_QueenAnimationIdle
	dw RaijinAnimationIdle
	dw KaruraAnimationIdle
	dw StagbeetleAnimationIdle
	dw BullAnimationIdle
	dw CarpAnimationIdle
	dw InkanyambaAnimationIdle
	dw PlesiosaurAnimationIdle
	dw SlimeAnimationIdle
	dw WolfAnimationIdle
	dw Wet_DogAnimationIdle
	dw GreyhoundAnimationIdle
	dw Hot_DogAnimationIdle
	dw LopolyfaceAnimationIdle
	dw NautilusAnimationIdle
	dw CuttlefishAnimationIdle
	dw Shoe_CrabAnimationIdle
	dw SeascorpioAnimationIdle
	dw PteranodonAnimationIdle
	dw PandaAnimationIdle
	dw YetiAnimationIdle
	dw ThundabirdAnimationIdle
	dw FirebirdAnimationIdle
	dw SerpentAnimationIdle
	dw LeviathanAnimationIdle
	dw MascotAnimationIdle
	dw WendigoAnimationIdle
	dw BrainAnimationIdle
	dw ChikoritaAnimationIdle
	dw KoalaAnimationIdle
	dw SlothAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw MonitorAnimationIdle
	dw CrocodileAnimationIdle
	dw SentretAnimationIdle
	dw FerretAnimationIdle
	dw HoothootAnimationIdle
	dw HornedowlAnimationIdle
	dw LedybaAnimationIdle
	dw FireflyAnimationIdle
	dw SpinarakAnimationIdle
	dw WaspAnimationIdle
	dw Big_BatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw GerbilAnimationIdle
	dw CleffaAnimationIdle
	dw BalloonAnimationIdle
	dw Hobo_ClownAnimationIdle
	dw BadClownAnimationIdle
	dw KakapoAnimationIdle
	dw QuetzalAnimationIdle
	dw LambAnimationIdle
	dw SheepAnimationIdle
	dw RamAnimationIdle
	dw Hula_GirlAnimationIdle
	dw Water_RatAnimationIdle
	dw RabbitAnimationIdle
	dw Fake_BushAnimationIdle
	dw FrogAnimationIdle
	dw HoppipAnimationIdle
	dw DaisyAnimationIdle
	dw DandelionAnimationIdle
	dw ChimpanzeeAnimationIdle
	dw SeedAnimationIdle
	dw SunflowerAnimationIdle
	dw DragonflyAnimationIdle
	dw Shags2DopeAnimationIdle
	dw Violent_JAnimationIdle
	dw TerrierAnimationIdle
	dw Xolo_DogAnimationIdle
	dw CrowAnimationIdle
	dw WarlockAnimationIdle
	dw BansheeAnimationIdle
	dw LettahAnimationIdle
	dw RolypolyAnimationIdle
	dw GiraffeAnimationIdle
	dw PineconeAnimationIdle
	dw FortressAnimationIdle
	dw TsuchinokoAnimationIdle
	dw GligarAnimationIdle
	dw DeathwormAnimationIdle
	dw FrenchieAnimationIdle
	dw BulldogAnimationIdle
	dw BlowfishAnimationIdle
	dw MantidflyAnimationIdle
	dw ScalebugAnimationIdle
	dw BeetleAnimationIdle
	dw WeaselAnimationIdle
	dw TeddybearAnimationIdle
	dw BearAnimationIdle
	dw SlugAnimationIdle
	dw SnailAnimationIdle
	dw BoarAnimationIdle
	dw MammothAnimationIdle
	dw CoralAnimationIdle
	dw RemoraAnimationIdle
	dw OctopusAnimationIdle
	dw SantaAnimationIdle
	dw MantaAnimationIdle
	dw CondorAnimationIdle
	dw RottweilerAnimationIdle
	dw DobermanAnimationIdle
	dw Sea_DragonAnimationIdle
	dw ElebabyAnimationIdle
	dw ElephantAnimationIdle
	dw LopolykiwiAnimationIdle
	dw ElkAnimationIdle
	dw ArtistAnimationIdle
	dw John_CenaAnimationIdle
	dw DreidelAnimationIdle
	dw BowlcutAnimationIdle
	dw PlugAnimationIdle
	dw BoobyAnimationIdle
	dw CowAnimationIdle
	dw BlisseyAnimationIdle
	dw BarghestAnimationIdle
	dw CerberusAnimationIdle
	dw FenrirAnimationIdle
	dw RaptorAnimationIdle
	dw IronmaidenAnimationIdle
	dw TrexAnimationIdle
	dw RyujinAnimationIdle
	dw PhoenixAnimationIdle
	dw CelebiAnimationIdle
